### ISSUE TITLE
MailChimp Sync - Segments?

### ISSUE THREAD

**Issue by tjpatter** [BEMADEV/Rock#129]
What are the recommended practices around using this plugin in regards to structuring audiences & segments?

We were hoping that the sync routine would also have the ability to populate an audience and corresponding groups (or tag) segments based upon segment information coming out of RockRMS. Instead, it appears that this plugin only synchronizes at the audience level. 

How hard would it be to add it segment information to the routine? Alternatively, is there a better way we should be thinking about the setup inside of MailChimp to accommodate our goals?

**Comment by tcavaletto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mailchimp: Implement Tagging](https://trello.com/c/B3j3eU11/68-mailchimp-implement-tagging)
