### ISSUE TITLE
Mailchimp Sync plugin - daily exceptions / list membership not updating

### ISSUE THREAD

**Issue by holyaxemaster** [BEMADEV/Rock#147]
A new Communication List we created will not push any members to its corresponding Mailchimp audience.  The Mailchimp Sync job shows "Success" daily when I look at its Job History, but I found a couple errors in Exception List related to the plugin.  It even looks like the sync tool may not have been working at all for any lists/audiences for a couple of weeks.  See exceptions below:

1. System Settings > Exception List
2. "Error occurred importing Mailchimp audience (INSERTLISTNAME)..."
3. click to view Exception Occurrences
4. same error repeats for all lists being synced since 10/9/20

1. System Settings > Exception List
2. "##Plugin Migration error occurred in org.ourcitychurch.ConnectionRequestDigest, AddSystemData##"
3. click to view Exception Occurrences
4. scrolled down a bit to also see several "##Plugin Migration error occurred in com.bemaservices.MailChimp, CreateDb##"

**Expected behavior:**

Members of selected Communication Lists should sync/push to corresponding Mailchimp audience

**Actual behavior:**

Sync tool is throwing exceptions and lists/audiences are not syncing

### Versions

* **Rock Version:** Rock McKinley 10.3 (1.10.3.7)
* **Client Culture Setting:** en-US

**Comment by tcavaletto** [comment]
@holyaxemaster In the Migration errors for the connection request digest and Mailchimp, what errors exactly are you seeing? This sounds like Rock trying to add an attribute qualifier where one already exists. Could you also give me the error occurring when importing the Mailchimp audience? This is most likely due to a disconnect between Rock and Mailchimp.

**Comment by holyaxemaster** [comment]
@tcavaletto Sorry for late response, I've attached a screenshot of the audience import error.  I need to track down the connection request digest error specific to Mailchimp, will upload soon.  Thanks
<img width="1298" alt="Screen Shot 2020-11-19 at 11 13 58 AM" src="https://user-images.githubusercontent.com/64667541/99713456-2ff56780-2a59-11eb-994c-079f6f7ce6d1.png">

**Comment by tcavaletto** [comment]
@holyaxemaster It looks like there's another exception hidden from view that contains what actually went wrong. If you grab the exception id from the exception labeled 'An error occurred while executing the command definition' (In this case 481065) and run the following SQL:
Select *
From ExceptionLog
Where ParentId = EXCEPTION_ID

Could you send me the results you get?

**Comment by tcavaletto** [comment]
Closed due to inactivity
