### ISSUE TITLE
Remote Check Deposit Plugin Error

### ISSUE THREAD

**Issue by darringraham** [BEMADEV/Rock#152]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We get a message when we select a number of batches to deposit and click the button to start the process

### Steps to Reproduce

1. Go to the Remote Deposit page: 'https://rock.flatironschurch.com/page/712'
2. Select the Open batches 
3. Click the down arrow icon at the far bottom right of the page.
4. See error:
Error

Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at RockWeb.Plugins.com_bemaservices.RemoteCheckDeposit.RemoteDepositExport.ValidateSelection()
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Expected behavior:**

The BEMA plugin should create a check deposit file that we can upload to our bank as usual.

**Actual behavior:**

No file is created and the above error is returned.

### Versions

* **Rock Version:** [Rock McKinley 11.2 (1.11.2.1)]
* **Client Culture Setting:** [en-US]

**Comment by sam-crisp** [comment]
@darringraham This first not found error was previously fixed in a version release of the Plugin. 
I would recommend downloading the Rock Shop version and upgrading to the latest and greatest.
