### ISSUE TITLE
NOT A BUG - just feedback for HR Management Plugin

### ISSUE THREAD

**Issue by timlem** [BEMADEV/Rock#160]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Just two suggestions/feedback. Change the entry form to say "Hours Per Day" instead of "Hours / Day". Our staff was really confused by that.
Give an option to hide not use "Exclude Weekends". Some Staff work Fridays, some don't. Most work Sundays. I can't think of any instance where we want to include weekends.

### Steps to Reproduce

1. Since this is not actually a bug I'm not sure this is needed. :)

**Expected behavior:**

N/A

**Actual behavior:**

N/A

### Versions

* **Rock Version:** [11.3]
* **Client Culture Setting:** [En-US]

**Comment by timlem** [comment]
https://soapbox.wistia.com/videos/WGEVz4j4hL

**Comment by tcavaletto** [comment]
@timlem The workflow entry is actually managed by the PTO Request workflow type. If you navigate to that workflow type under general settings, you can modify it to change the Hours / Day label and hide the Exclude Weekends control.
