### ISSUE TITLE
Job creates two sets of allocations randomly for some people

### ISSUE THREAD

**Issue by timlem** [BEMADEV/Rock#163]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When we first installed the plugin and ran the allocation job, we had 3 or 4 staff members have double the sets of allocations. So for example I would receive two PTO for 80 hours and two sick time for 40 hours. It only happened to 3 or 4 staff. We went in and deleted the extra allocations and reran the job and did not recreate the 2nd set. 

We just changed the job to go ahead and create allocations for next year and when we did we had 3 staff members again have double allocation sets created. These were 3 different staff members than the ones before.

Here are my job settings:
![Screen Shot 2020-11-30 at 5 16 50 PM](https://user-images.githubusercontent.com/1486523/100672319-c0705980-332f-11eb-86ba-aad3ee93bf94.png)

### Steps to Reproduce

1. Go to Jobs Administration and run job as if it was for a new year
2. Look through staff to see if anyone has double allocations created

**Expected behavior:**

I would expect for double allocations not to be created.

**Actual behavior:**

Double Allocations are created seemingly randomly for some staff

### Versions

* **Rock Version:** [11.3
* **Client Culture Setting:** [En-US]

**Comment by tcavaletto** [comment]
@timlem Could you send me a screenshot of what your brackets look like? And any remaining duplicates if you still have them.

**Comment by timlem** [comment]
@tcavaletto I'm sorry - I missed your response somehow. I am going to close this as it is not an issue for us now but if I see it again I'll let you know and send screenshots before we manually fix it
