### ISSUE TITLE
Cannot create PTO Request

### ISSUE THREAD

**Issue by jrockman13** [BEMADEV/Rock#169]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When trying to create a PTO request, the "+" sign does nothing. This happens on the PTO Request page under HR Management and on the employee's person profile page.

### Steps to Reproduce

1. Go to person profile page - HR
2. Click on '+' to create new PTO request

**Expected behavior:**

A form would open to allow user to input new PTO request

**Actual behavior:**

Nothing happens!

### Versions

* **Rock Version:** 11.3
* **Client Culture Setting:** EN-us
* **Plugin Version:** 1.1.0.1

**Comment by tcavaletto** [comment]
Issue solved: Ended up being a migration error.
