### ISSUE TITLE
Feature request: BEMA MinistrySafe plug-in to support multiple awareness training results

### ISSUE THREAD

**Issue by edcylam** [BEMADEV/Rock#175]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Allows the BEMA MinistrySafe Integration to support multiple awareness training results

### Steps to Reproduce

1. Some of our staff members and volunteers are required to take more than one MinistrySafe training. 

**Expected behavior:** 

The plug-in would be able to display the results of all their completed awareness trainings in the profile's extended attributes section.

**Actual behavior:** 

Currently, the plug-in can support only the training result of one Ministryawareness training.

### Versions

* **Rock Version:** 11.3  
* **Client Culture Setting:** EN-US

**Comment by tcavaletto** [comment]
Added feature request to our internal roadmap for the next MinistrySafe release
