### ISSUE TITLE
Cancelled PTO hours not refunded to allocation

### ISSUE THREAD

**Issue by jrockman13** [BEMADEV/Rock#196]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When a user cancels a PTO request, the hours are not returned to their application. They are displayed as so on the PTO allocations, but when a user tries to submit a new PTO request, the hours are gone.

### Steps to Reproduce

1. Create a PTO request and have it approved.
2. Cancel the PTO request (i did NOT notify supervisor)
3. Note that the hours available appear correct on the PTO allocation list
4. Try to create a new PTO request using the same allocation.
5. Note that the hours are not available.

![image](https://user-images.githubusercontent.com/22159658/108876235-a14a3680-75c3-11eb-9a85-a4e2a12ef45f.png)

![image](https://user-images.githubusercontent.com/22159658/108876430-d060a800-75c3-11eb-8a8e-58e70f46a305.png)

**Expected behavior:** 

hours from cancelled PTO request should be available to be rebooked

**Actual behavior:** 

The hours were not available to be rebooked

### Versions

* **Rock Version:** 1.11.3.1 
* **Client Culture Setting:** EN-us

**Comment by timlem** [comment]
I'm seeing this as well.

**Comment by jrockman13** [comment]
Hmm. something isn't working:

![image](https://user-images.githubusercontent.com/22159658/109046270-2a33a180-769a-11eb-94b2-f3a3045e8b90.png)

It's displaying the correct total, but I'm trying to put in a request for 72 hours and it's blocking me.

**Comment by tcavaletto** [comment]
If you go to the Pto Request Workflow Type > Add / Modify Request Activity > Check Remaining Hours action, and replace the code with this:
`{% assign requestHours = Workflow | Attribute:'RequestedHours' %}

{% assign ptoAllocationGuid = Workflow | Attribute:'PTOAllocation','RawValue' %}
{% if ptoAllocationGuid == empty %}
    {% assign ptoRequest = Workflow | Attribute:'PTORequest','Object' %}
    {% assign ptoAllocationGuid = ptoRequest.PtoAllocation.Guid %}
{% endif %}

{% ptoallocation where:'Guid == "{{ptoAllocationGuid}}"' %}
    {% for ptoAllocation in ptoallocationItems %}
        {% assign totalHours = ptoAllocation.Hours %}
        {% assign takenHours = 0.0 %}
        {% for request in ptoAllocation.PtoRequests %}
            {% if request.PtoRequestApprovalState == 1 %}
                {% assign takenHours = takenHours | Plus:request.Hours %}
            {% endif %}
        {% endfor %}
        {% assign remainingHours = totalHours | Minus:takenHours %}
    {% endfor %}
{% endptoallocation %}
{% assign remainingHours = remainingHours | Minus:requestHours %}

{{ remainingHours }}`

Does it resolve your issue? If so I'll add an update that fixes it for everyone.

**Comment by jrockman13** [comment]
It worked!
