### ISSUE TITLE
MailChimp Integration Plug-in Failed to Install Correctly

### ISSUE THREAD

**Issue by timbarley-gt** [BEMADEV/Rock#28]
Not sure if this the best place to get support for this plugin, but the Support Link in the Rock Shop sent me to this GH Issues page. I installed the MailChimp Integration Plug-in. It shows installed in the Rock Shop, but there is nothing under Installed Plug-ins. There is no MailChimp job in Job Administration and I am now get the following exceptions: "Unable to load MEF from com.bemaservices.MailChimp, Version=1.0.0.1, Culture=neutral, PublicKeyToken=null" and "Could not load file or assembly 'MailChimp.Net.V3, Version=2.1.0.0, Culture=neutral, PublicKeyToken=[removed for submitting this issue]' or one of its dependencies. The system cannot find the file specified.".

Thanks

**Comment by tcavaletto** [comment]
@timbarley-gt  What version of Rock did you install it on?

**Comment by timbarley-gt** [comment]
I'm on v9.4

**Comment by tcavaletto** [comment]
If you go to System Information ( the small i button in the bottom right hand corner) > Diagnostics, can you post what information you see under Plugin Assemblies?

**Comment by timbarley-gt** [comment]
@tcavaletto Here's our current config:

Plugin Assembly | Migration Name | Number
cc.newspring.AttendedCheckIn | FixSpecialNeeds | 2
com.blueboxmoon.AcmeCertificate | AddRenewalJob | 4
com.blueboxmoon.WorkflowStimPack | AddRemoveSecurityFromEntity | 6
com.bricksandmortarstudio.checkinextensions | FixIndividualAttendedDurationBadge | 5
com.centralaz.RoomManagement | ReservationType | 19
com.minecartstudio.PbxSwitchvox | UpdateInteractionChannelLava | 4
com.minecartstudio.PdfToolkit | InitalSetup | 1
com.minecartstudio.TextToWorkflow | RenameDomain | 3
com.shepherdchurch.RockShopNotifications | SetBlockSecurity | 3
com.shepherdchurch.SurveySystem | AddSurveyWorkflow | 9
com.SimpleDonation | InstallNotification | 11
org.secc.GroupTypeChangeTool | PageMigration | 1
org.secc.PastoralCare | Pastoral_FixLegacyLava | 6
Rock | DiscProfileAttributeFix | 92
Rock.Checkr | Checkr_UpdateExistingPmmPackages | 9
Rock.Migrations | StatementProcs | 6
Rock.StatementGenerator | StatementGeneratorMoreOptions | 3

**Comment by ConnectionChurch** [comment]
We are also having this same problem. Here is our data:

Plugin Assembly | Migration Name | Number
-- | -- | --
cc.newspring.AttendedCheckIn | FixSpecialNeeds | 2
com.blueboxmoon.AcmeCertificate | AddRenewalJob | 4
com.blueboxmoon.WorkflowStimPack | AddProcessIncomingSMS | 4
com.centralaz.RoomManagement | ReservationType | 19
com.securegive.RockPlugin | RockPlugin | 1
org.secc.GroupTypeChangeTool | PageMigration | 1
org.secc.PastoralCare | Pastoral_AddVisitCancel | 5
Rock | PrayerRequestCommentsNotificationEmailTemplate | 95
Rock.Checkr | Checkr_UpdateExistingPmmPackages | 9
Rock.Migrations | StatementProcs | 6
Rock.StatementGenerator | StatementGeneratorMoreOptions | 3

**Comment by ConnectionChurch** [comment]
We are on version 10.1

**Comment by tcavaletto** [comment]
@timbarley-gt @ConnectionChurch We've added an update to the plugin to fix this issue. Let us know if you continue to have problems after downloading it.
