### ISSUE TITLE
Ministry Safe plugin not installed correctly v 10.2 or 10.1

### ISSUE THREAD

**Issue by karenn-ccbc** [BEMADEV/Rock#32]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

I Asked on the Community and installed in both our production environment 10.2 and our Dev environment v 10.1, I am wondering if the workflow, security role, attributes and Global attribute for the API do not show up in Rock until the API has been configured in Ministry Safe? I was expecting to see those items in Rock so that I could begin to configure them in our system before enabling the API with Ministry Safe. 
Our Rock shop shows the package is installed

### Steps to Reproduce

1. Go to 'Rock Shop'
2. Click on 'Install Ministry Safe Plugin after purchase'
3. Rock restarts and note that Package is installed
4. Go to Rock and check for the Workflow, Ministry Safe security Role, Person Attributes, Global Attribute for the Ministry Safe API key

**Expected behavior:**

Expected to find these items in Rock, to be able to configure them.

**Actual behavior:**

Nothing has been added to Rock

### Versions

* **Rock Version:** [10.1 or 10.2]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by karenn-ccbc** [comment]
Good news: the plugin failed to install properly:

4/19/2020 8:48:36 PM,System.Data.SqlClient.SqlException,"Invalid object name 'PersonBadge'.","   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Rock.Plugin.Migration.Sql(String sql)
   at com.bemaservices.MinistrySafe.Migrations.Data.Up()
   at RockWeb.Global.MigratePlugins(RockContext rockContext)"
4/19/2020 8:48:36 PM,System.Exception,"##Plugin Migration error occurred in com.bemaservices.MinistrySafe, Data##","   at RockWeb.Global.MigratePlugins(RockContext rockContext)"

Bad news: Rock thinks everything is installed correctly and we are now sitting smack in the middle of undefined territory.

**Comment by karenn-ccbc** [comment]
Please advise on how we are to attempt to reinstall the plugin  (WITHOUT rolling back )

**Comment by karenn-ccbc** [comment]
According to this it appears that PersonBadge was renamed Badge
https://github.com/SparkDevNetwork/Rock/blob/faab86ba3b8d299ae5603f4b4c2b532ca57356aa/Rock.Migrations/Migrations/Version%2010.0/Version%201.10.0/201907182111279_Badges.cs#L32

**Comment by tcavaletto** [comment]
Hello Karen,
We've created a fix for this issue (https://github.com/BEMADEV/Rock/commit/d502b72f3856841f4d2a3e2431e34406f9933729) and submitted it to the Rock Shop for review. You should see the update within the next day or two. Let us know if you have any issues with it after the update. You shouldn't need to uninstall or reinstall the plugin, just update it and it'll run everything it needs to normally. Let me know if that doesn't work!

**Comment by tcavaletto** [comment]
Karen,
The package update is now in the store, so I'm closing this issue. Let me know if you have any other problems!

**Comment by karenn-ccbc** [comment]
Thanks we installed update!

Karen Norris
