### ISSUE TITLE
Exception from Connections Digest Job

### ISSUE THREAD

**Issue by morganw93** [BEMADEV/Rock#40]
### Description

This exception is being thrown: 
### Steps to Reproduce

<img width="1240" alt="Screen Shot 2020-05-01 at 6 22 28 PM" src="https://user-images.githubusercontent.com/30188136/80848419-cf93fb00-8bd8-11ea-900c-9e596e468472.png">

### Versions

* **Rock Version:** 10.2
* **Client Culture Setting:** en-us

**Comment by tcavaletto** [comment]
Fixed in https://github.com/BEMADEV/Rock/commit/22eec87d9f0b096d035af73c9a5f8352aa865d76. @morganw93, a new version has been submitted to the Rock Shop for review and should be available for download within 1-2 days.
