### ISSUE TITLE
Mail Chimp Sync job fails with NRE

### ISSUE THREAD

**Issue by cabal95** [BEMADEV/Rock#71]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When attempting to run the Mail Chimp Sync job, it fails with a Null Reference Exception. The stack trace unfortunately does not provide much information.

<img width="858" alt="2020-06-08 08_54_19-Window" src="https://user-images.githubusercontent.com/1119863/84052779-dc3d0900-a965-11ea-9687-985e1c35b197.png">

Please let us know how we can help troubleshoot the cause and what information we can provide.

### Versions

* **Rock Version:** 10.2
* **Plugin Version:** 1.0.0.6
* **Client Culture Setting:** en-Us

**Comment by cabal95** [comment]
@tcavaletto Installed version 1.0.0.9 and still getting the error, but here is the additionally logged information:

![image](https://user-images.githubusercontent.com/1119863/84717184-f8bedf80-af29-11ea-8b9a-2c6658c04e7d.png)

**Comment by tcavaletto** [comment]
@cabal95 I've pushed a 1.0.0.10 version to the store with better error handling when grabbing MailChimp lists. Let me know if that solves your problem / what errors you still get after installing it.

**Comment by cabal95** [comment]
@tcavaletto I  updated  to version 1.0.0.11 tonight  and tried  to  run the job again. Still get an error, but it  did  log  a new error:

There was also the previous NRE exception logged  as  well.

<img width="1148" alt="Screen Shot 2020-07-21 at 6 04 11 PM" src="https://user-images.githubusercontent.com/1119863/88122164-b3bb4800-cb7c-11ea-88dd-3e880b6677f6.png">

**Comment by tcavaletto** [comment]
@cabal95 Looks like this is a bug within the MailChimp library we use (https://github.com/brandonseydel/MailChimp.Net), so once we get a fix I'll submit it to that repo. Do you have any audiences with non-alphanumeric characters?

**Comment by cabal95** [comment]
That  I'm not sure of. The person that was in  charge of  this particular  project has moved on to  other  things so I will  have to  dig around to see who  is  in charge now and  who  has the mailchimp  login credentials to  check.

**Comment by cabal95** [comment]
@tcavaletto Okay, we finally tracked  down some more information.  It looks  like  the person  who was in charge of the Mailchimp account  closed the account (!?!?!) and  never bothered to tell us even though we were not ready for them to do so.  Suffice to say, that is probably the core  internal issue is that it's trying to sync to an account that no longer exists.

I'm happy to keep updating and testing patches to help you figure  out  why it's throwing a NRE instead of successfully detecting that scenario and displaying a more helpful message. Otherwise we can just consider this closed I guess.

**Comment by tcavaletto** [comment]
@cabal95 I've added more information to the error message this generates (https://github.com/BEMADEV/Rock/commit/030679cfb6040bc9e726875e9473961311902ea0, https://github.com/BEMADEV/Rock/commit/37cde569acf06f5e7189508e6297935e874a2d39) to help clarify the source of this issue, so I'm marking it as closed. Thanks for your help and patience with this!
