### ISSUE TITLE
Pastoral Care Plugin - Shared Attribute not available on Care Item entry form

### ISSUE THREAD

**Issue by DerekMangrum** [BEMADEV/Rock#84]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Shared Attributes not showing up on Care Item Detail Form.

### Steps to Reproduce

1. Installed and configured plugin, including creating Care Types and a Shared Attribute.
2. Added a Care Item. The Shared Attribute was not displayed on the Care Item Form.

**Expected behavior:** 

I expected to see the Shared Attribute on the Care Item entry form.

**Actual behavior:** 

Shared Item not displayed.

### Versions

* **Rock Version:** 10.2
* **Client Culture Setting:** Win10, Firefox

**Comment by tcavaletto** [comment]
I've pushed a new version of the plugin to the Rock Shop that fixes this issue.
